### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by mormahr**
Just a maintenance update, now using the current bluebird and lodash versions, so it works nicely along other modules ☺️

### CODE REVIEW

**Comment by mormahr** [comment]
Main reason besides contributing to a favorite project of mine was, that `express-promise-router` currently gets its own node_modules folder because the versions of bluebird and lodash are incompatible with some newer versions

**Comment by mormahr** [comment]
Updated the dev dependencies as well ☺️

**Comment by alex-whitney** [comment]
Thanks for bumping the dependencies. I know it's been a while since you submitted this, and I hate to hold this up for styling, but you've got some mixed tabs/spaces in the tests.

**Comment by mormahr** [comment]
May i suggest adding a .editorconfig which would reduce this kind of problem. ☺️

In this case: 
```
[*.js]
indent_style=space
indent_size=4
```

I can, of course, add this myself and submit another pull request if you'd like

**Comment by holm** [comment]
Would be very nice to get this merged

**Pull request merged**
